import type { Metadata } from "next";

import "./globals.css";
import { monserrat } from "@/app/fonts/fonts";



export const metadata: Metadata = {
  title: "CasaVerde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monserrat.className}>{children}</body>
    </html>
  );
}
